# Generated by Django 4.2.1 on 2023-05-07 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=100, verbose_name='brand')),
                ('color', models.CharField(max_length=100, verbose_name='color')),
                ('velume', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Обьем')),
                ('image', models.ImageField(upload_to='images/car', verbose_name='image')),
                ('car_type', models.IntegerField(choices=[(1, 'Седан'), (2, 'Хечбек'), (3, 'Универсал'), (4, 'Купе')], verbose_name='Пользователь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
